### ISSUE TITLE
where feets

### ISSUE THREAD

**Issue by hyperarcher** [EmilieFox/please-keep-using-10#5]
Instructions unclear, pictures of feets are not present in the repo.

Ultra best regards,
a simping idiot

**Comment by EmilieFox** [comment]
They'll be delivered in 3-4 business weeks along with a bonus restraining order

**Comment by hyperarcher** [comment]
I prefer to receive them when pigs start to fly (or once chickens get teeths)

**Comment by EmilieFox** [comment]
Noted, restraining order still on the way though
